runtime: python39

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'lateral-imagery-415421-1823d261a821.json'

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto